---
title: "TT_GreatLakesFish"
author: "Jeff Grayum"
date: "6/9/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggthemes)
#install.packages("ggExtra")
library(ggExtra)
#install.packages("ggfortify")
library(ggfortify)
#install.packages("sweep")
library(sweep)
#install.packages("timetk")
library(timetk)
library(forecast)
library(lubridate)
```

Loading datasets.
```{r}
tt <- tuesdata <- tidytuesdayR::tt_load('2021-06-08')

fishing <- tt$fishing %>%
  filter(values >= 0) %>%
  mutate(species = str_replace(str_to_title(species), "([^s])s$", "\\1")) 
  

stocked <- tt$stocked

stocked %>%
  view()
```


```{r}
fishing %>%
  filter(!is.na(grand_total), 
         lake == "Erie") %>%
  mutate(species = fct_lump(species, 6)) %>%
  filter(species != "Other",
         year > 1920) %>%
  group_by(year, lake, species) %>%
  summarize(yr_sp_total = sum(grand_total)) %>%
  ggplot(aes(year, yr_sp_total, fill = species)) +
  geom_col() +
  facet_wrap(~ species, scales = "free_y") +
  scale_y_continuous(labels = comma) +
  theme_fivethirtyeight() +
  labs(x = "Year",
       y = "Total catch",
       title = "Yearly species totals caught in Lake Erie",
       caption = "Source: Great Lakes Fishery Commission") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none")

fishing %>%
  count(lake, sort = TRUE)


fishing %>%
  filter(!is.na(grand_total), 
         lake == "Superior") %>%
  mutate(species = fct_lump(species, 6)) %>%
  filter(species != "Other",
         year > 1920) %>%
  group_by(year, species) %>%
  summarize(yr_sp_total = sum(grand_total)) %>%
  ggplot(aes(year, yr_sp_total, fill = species)) +
  geom_col() +
  facet_wrap(~ species, scales = "free_y") +
  scale_y_continuous(labels = comma) +
  theme_fivethirtyeight() +
  labs(x = "Year",
       y = "Total catch",
       title = "Yearly species totals caught in Lake Superior",
       caption = "Source: Great Lakes Fishery Commission") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none")

fishing %>%
  filter(!is.na(grand_total), 
         lake == "Huron") %>%
  mutate(species = fct_lump(species, 6)) %>%
  filter(species != "Other",
         year > 1920) %>%
  group_by(year, species) %>%
  summarize(yr_sp_total = sum(grand_total)) %>%
  ggplot(aes(year, yr_sp_total, fill = species)) +
  geom_col() +
  facet_wrap(~ species, scales = "free_y") +
  scale_y_continuous(labels = comma) +
  theme_fivethirtyeight() +
  labs(x = "Year",
       y = "Total catch",
       title = "Yearly species totals caught in Lake Huron",
       caption = "Source: Great Lakes Fishery Commission") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none")
```

Now for David's stuff.
```{r}
fishing %>%
  ggplot(aes(grand_total)) +
  geom_histogram()

fishing %>%
  ggplot(aes(grand_total + 1)) +
  geom_histogram() +
  scale_x_log10(labels = comma) +
  theme_fivethirtyeight() +
  labs(x = "Grand total (log scale + 1)",
       y = "Count",
       title = "Histogram: Grand totals") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

fishing %>%
  ggplot(aes(values + 1)) +
  geom_histogram() +
  scale_x_log10(labels = comma) +
  theme_fivethirtyeight() +
  labs(x = "Value (log scale + 1)",
       y = "Count",
       title = "Histogram: Values") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

fishing %>%
  count(lake)

fishing %>%
  count(species, sort = TRUE)

fishing %>%
  group_by(year, lake, species) %>%
  summarize(total_values = sum(values, na.rm = TRUE),
            first_grand_total = min(grand_total, na.rm = TRUE),
            n_grand_total = n_distinct(grand_total)) %>%
  filter(year >= 2000) %>%
  ungroup() %>%
  count(n_grand_total)
```


```{r}
fishing %>%
  group_by(year) %>%
  summarize(total_fish = sum(values, na.rm = TRUE)) %>%
  ggplot(aes(year, total_fish)) +
  geom_line() +
  theme_fivethirtyeight() +
  labs(x = "Year",
       y = "Total fish",
       title = "Total fish caught each year in the Great Lakes",
       caption = "Source: Great Lakes Fishery Commission") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

#Let's make ourselves a quick function
summarize_fishing <- function(tbl) {
  tbl %>%
    summarize(n_obs = n(),
              total_fish = sum(values, na.rm = TRUE)) %>%
    arrange(desc(total_fish))
}

fishing %>%
  group_by(year) %>%
  summarize_fishing() %>%
  ggplot(aes(year, total_fish)) +
  geom_line() +
  theme_fivethirtyeight() +
  labs(x = "Year",
       y = "Total fish",
       title = "Total fish caught each year in the Great Lakes",
       caption = "Source: Great Lakes Fishery Commission") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

fishing %>%
  group_by(decade = 10 * year %/% 10) %>%
  summarize(total_fish = sum(values, na.rm = TRUE)) %>%
  ggplot(aes(decade, total_fish)) +
  geom_col() +
  theme_fivethirtyeight() +
  scale_y_continuous(labels = comma_format()) +
  labs(x = "Decade",
       y = "Total fish",
       title = "Total fish caught each year in the Great Lakes",
       caption = "Source: Great Lakes Fishery Commission") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

fishing %>%
  group_by(species) %>%
  summarize_fishing()

fishing %>%
  mutate(species = fct_lump(species, 6, w = values),
         species = fct_reorder(species, values, sum)) %>%
  group_by(decade = 10 * year %/% 10,
           species) %>%
  summarize(total_fish = sum(values, na.rm = TRUE)) %>%
  ggplot(aes(decade, total_fish, fill = species)) +
  geom_col() +
  theme_few() +
  scale_y_continuous(labels = comma_format()) +
  labs(x = "Decade",
       y = "Total fish",
       title = "Total fish caught each year in the Great Lakes",
       caption = "Source: Great Lakes Fishery Commission") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "bottom")

fishing %>%
  mutate(species = fct_lump(species, 5, w = values),
         species = fct_reorder(species, values, sum)) %>%
  group_by(decade = 10 * year %/% 10,
           species) %>%
  summarize(total_fish = sum(values, na.rm = TRUE)) %>%
  ggplot(aes(decade, total_fish, fill = species)) +
  geom_col() +
  theme_few() +
  facet_wrap(~species) +
  scale_y_continuous(labels = comma_format()) +
  labs(x = "Decade",
       y = "Total fish",
       title = "Total fish caught each year in the Great Lakes",
       caption = "Source: Great Lakes Fishery Commission") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none")

fishing %>%
  mutate(species = fct_lump(species, 5, w = values),
         species = fct_reorder(species, values, sum)) %>%
  group_by(decade = 10 * year %/% 10,
           species) %>%
  summarize(total_fish = sum(values, na.rm = TRUE)) %>%
  ggplot(aes(decade, total_fish, fill = species)) +
  geom_col() +
  theme_fivethirtyeight() +
  facet_wrap(~species) +
  scale_y_continuous(labels = comma_format()) +
  labs(x = "Decade",
       y = "Total fish",
       title = "Total fish caught each year in the Great Lakes",
       caption = "Source: Great Lakes Fishery Commission") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none")

fishing %>%
  mutate(species = fct_lump(species, 15, w = values),
         species = fct_reorder(species, -values, sum)) %>%
  group_by(decade = 10 * year %/% 10,
           species) %>%
  summarize(total_fish = sum(values, na.rm = TRUE)) %>%
  ggplot(aes(decade, total_fish, fill = species)) +
  geom_area() +
  theme_few() +
  facet_wrap(~species) +
  scale_y_continuous(labels = comma_format()) +
  labs(x = "Decade",
       y = "Total fish",
       title = "Yearly fish production in the Great Lakes",
       caption = "Source: Great Lakes Fishery Commission") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none")


#Oh boy we gotta do some cleaning!
fishing %>%
  filter(str_detect(species, "Cisco")) %>%
  mutate(species = fct_lump(species, 8, w = values),
         species = fct_reorder(species, -values, sum)) %>%
  group_by(decade = 10 * year %/% 10,
           species) %>%
  summarize(total_fish = sum(values, na.rm = TRUE)) %>%
  ggplot(aes(decade, total_fish, fill = species)) +
  geom_area() +
  theme_fivethirtyeight() +
  facet_wrap(~species) +
  scale_y_continuous(labels = comma_format()) +
  labs(x = "Decade",
       y = "Total fish",
       title = "Yearly fish production in the Great Lakes",
       caption = "Source: Great Lakes Fishery Commission") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none")

fishing %>%
  group_by(species, year) %>%
  summarize_fishing() %>%
  summarize(total_fish = sum(total_fish),
            peak_year = year[which.max(total_fish)]) %>%
  arrange(desc(total_fish)) %>%
  head(16) %>%
  mutate(species = fct_reorder(species, peak_year)) %>%
  ggplot(aes(peak_year, species)) +
  geom_point(aes(size = total_fish)) +
  theme_tufte() +
  scale_size_continuous(labels = comma_format()) +
  labs(x = "Year of peak prodcution",
       y = "Species",
       title = "Peak year of production for Great Lake's fish",
       caption = "Source: Great Lakes Fishery Commission",
       size = "Total catch") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

```


```{r}
fishing %>%
  mutate(lake = fct_reorder(lake, values, sum, .desc = TRUE)) %>%
  group_by(decade = 10 * year %/% 10,
           lake) %>%
  summarize_fishing() %>%
  ggplot(aes(decade, total_fish, fill = lake)) +
  geom_area() +
  scale_y_continuous(labels = comma_format()) +
  facet_wrap(~ lake) +
  theme_few() +
  theme(legend.position = "none",
        axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  labs(x = "Decade",
       y = "Total production per decade (thousands of pounds)",
       title = "Production across the Great Lakes over time")

by_lake_species <- fishing %>%
  filter(lake != "Saint Clair") %>%
  mutate(species = fct_lump(species, 15, w = values),
         species = fct_reorder(species, values, sum),
         lake = fct_reorder(lake, values, sum, .desc = TRUE)) %>% 
  group_by(lake, species) %>%
  summarize_fishing() 

by_lake_species %>%
  ggplot(aes(lake, species, fill = total_fish)) +
  geom_tile() +
  scale_fill_gradient2(low = "white", high = "darkblue", labels = comma) +
  theme(panel.grid = element_blank(),
        axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  expand_limits(fill = 0) +
  labs(x = "Lake",
       y = "Species",
       fill = "All time production") 

#Next we're going to normalize our data.
by_lake_species %>%
  group_by(lake) %>%
  mutate(pct = total_fish / sum(total_fish)) %>%
  ggplot(aes(lake, species, fill = pct)) +
  geom_tile() +
  scale_fill_gradient2(low = "white", high = "darkblue", labels = percent_format(accuracy = 1)) +
  theme(panel.grid = element_blank(),
        axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  expand_limits(fill = 0) +
  labs(x = "Lake",
       y = "Species",
       fill = "All time production") 
```

Let's look at our other dataset.
```{r}
stocked <- stocked %>%
  janitor::clean_names()

stocked %>%
  count(site, sort = TRUE)

stocked %>%
  count(st_site, sort = TRUE)

stocked %>%
  count(species, sort = TRUE)

stocked %>%
  ggplot(aes(year)) +
  geom_histogram(binwidth = 1) +
  theme_tufte() +
  labs(x = "Year",
       y = "Count",
       title = "Yearly distribution") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        panel.grid.major = element_blank()) +
  scale_y_continuous(labels = comma)



stocked %>%
  ggplot(aes(length)) +
  geom_histogram(bins = 200) +
theme_few() +
  labs(x = "Length (log scale)",
       y = "Count",
       title = "Length distribution") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        panel.grid.major = element_blank()) +
  scale_y_continuous(labels = comma) +
  scale_x_log10(labels = comma)

stocked %>%
  group_by(species) %>%
  summarize(median_length = median(length, na.rm = TRUE ))
```

YALL WANNA DO SOME FORECASTING
```{r}
fishing %>%
  filter(species == "Yellow Perch") %>%
  group_by(year, species) %>%
  summarize_fishing() %>%
  ggplot(aes(year, total_fish)) +
  geom_line() +
  theme_tufte() +
  labs(x = "Year",
       y = "Total Yellow Pearch",
       title = "Total Yellow Perch caught each year") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  scale_y_continuous(labels = comma)

by_year_species <- fishing %>%
  mutate(year = as.Date(paste0(year, "-01-01"))) %>%
  group_by(year, species) %>%
  summarize_fishing() %>%
  ungroup() %>%
  select(-n_obs)

yellow_perch <- by_year_species %>%
  filter(species == "Yellow Perch")

time_series <- yellow_perch %>%
  tk_ts(start = min(year(.$year)), freq = 1)

ets_mod <- by_year_species %>%
  filter(species == "Yellow Perch") %>%
  tk_ts(start = min(year(.$year)), freq = 1) %>%
  ets()

ets_mod %>%
  sw_tidy()

ets_mod %>%
  sw_augment() %>%
  ggplot(aes(index, .actual)) +
  geom_line() +
  geom_line(aes(y = .fitted), color = "blue") +
  theme_tufte() +
  labs(x = "Year",
       y = "Total production of Yellow Perch",
       title = "Actual production of Yellow Perch vs forecasted production (blue)")

decomp_fit_ets <- sw_tidy_decomp(ets_mod)
decomp_fit_ets

fcast <- ets_mod %>%
  forecast(h = 10)

fcast_holt <- time_series %>%
  holt()

fcast_ses <- ses(time_series)

autoplot(time_series) +
  autolayer(fcast_holt, series = "Holt", PI = FALSE) +
  autolayer(fcast_ses, series = "SES", PI = FALSE)
```

```{r}
carp <- by_year_species %>%
  filter(species == "Carp")

time_series <- carp %>%
  tk_ts(start = min(year(.$year)), freq = 1)

ets_mod <- by_year_species %>%
  filter(species == "Carp") %>%
  tk_ts(start = min(year(.$year)), freq = 1) %>%
  ets()

ets_mod %>%
  sw_augment() %>%
  ggplot(aes(index, .actual)) +
  geom_line() +
  geom_line(aes(y = .fitted), color = "blue") +
  theme_tufte() +
  labs(x = "Year",
       y = "Total production of Carp",
       title = "Actual production of Carp vs forecasted production (blue)")

decomp_fit_ets <- sw_tidy_decomp(ets_mod)
decomp_fit_ets

fcast <- ets_mod %>%
  forecast(h = 100)

fcast_holt <- time_series %>%
  holt()

fcast_ses <- ses(time_series)

time_series <- by_year_species %>%
  select(-species) %>%
  tk_ts(start = min(year(.$year)), freq = 1)

autoplot(time_series) +
  autolayer(fcast_holt, series = "Holt", PI = FALSE) +
  autolayer(fcast_ses, series = "SES", PI = FALSE)

forecast <- by_year_species %>%
  mutate(species = fct_lump(species, 8)) %>%
  group_by(year, species) %>%
  summarize(total_production = sum(total_fish), .groups = "drop") %>%
  nest(data = c(-species)) %>%
  mutate(time_series = map(data, ~ tk_ts(., start = min(year(.$year)), freq = 1))) %>%
  mutate(holt = map(time_series, holt, h = 20),
         ses = map(time_series, ses, h = 20)) 

sw_tidy(forecast$time_series[[1]])

sw_sweep(forecast$holt[[1]])

forecast %>%
  mutate(time_series_tidy = map(time_series, sw_tidy)) %>%
  unnest(time_series_tidy)

forecast %>%
  mutate(forecast_sweep = map(holt, sw_sweep)) %>%
  unnest(forecast_sweep) %>%
  ggplot(aes(index, total_production)) +
  geom_line() +
  geom_ribbon(aes(ymin = lo.80, ymax = hi.80), alpha = 0.2) +
  facet_wrap(~ species, scales = "free_y") +
  theme_solarized() +
  scale_y_continuous(labels = comma) +
  labs(title = "Forecasting fish production in the Great Lakes over two decades",
       x = "Year",
       y = "Total production",
       caption = "Source: Great Lakes Fishery Commission")
```

